// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package node

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Info struct {
	IP                   string   `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=Port,proto3" json:"Port,omitempty"`
	PubKey               []byte   `protobuf:"bytes,3,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	Role                 uint32   `protobuf:"varint,4,opt,name=Role,proto3" json:"Role,omitempty"`
	PeerID               []byte   `protobuf:"bytes,5,opt,name=PeerID,proto3" json:"PeerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *Info) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Info) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Info) GetRole() uint32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *Info) GetPeerID() []byte {
	if m != nil {
		return m.PeerID
	}
	return nil
}

type BlockchainSyncMessage struct {
	BlockHeight          int64    `protobuf:"varint,1,opt,name=BlockHeight,proto3" json:"BlockHeight,omitempty"`
	BlockHashes          []byte   `protobuf:"bytes,2,opt,name=BlockHashes,proto3" json:"BlockHashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockchainSyncMessage) Reset()         { *m = BlockchainSyncMessage{} }
func (m *BlockchainSyncMessage) String() string { return proto.CompactTextString(m) }
func (*BlockchainSyncMessage) ProtoMessage()    {}
func (*BlockchainSyncMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

func (m *BlockchainSyncMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockchainSyncMessage.Unmarshal(m, b)
}
func (m *BlockchainSyncMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockchainSyncMessage.Marshal(b, m, deterministic)
}
func (m *BlockchainSyncMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockchainSyncMessage.Merge(m, src)
}
func (m *BlockchainSyncMessage) XXX_Size() int {
	return xxx_messageInfo_BlockchainSyncMessage.Size(m)
}
func (m *BlockchainSyncMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockchainSyncMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BlockchainSyncMessage proto.InternalMessageInfo

func (m *BlockchainSyncMessage) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *BlockchainSyncMessage) GetBlockHashes() []byte {
	if m != nil {
		return m.BlockHashes
	}
	return nil
}

func init() {
	proto.RegisterType((*Info)(nil), "node.Info")
	proto.RegisterType((*BlockchainSyncMessage)(nil), "node.BlockchainSyncMessage")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x31, 0xcb, 0xc2, 0x30,
	0x10, 0x86, 0x49, 0x9b, 0xaf, 0xf0, 0x9d, 0xd5, 0x21, 0xa0, 0x64, 0x0c, 0x9d, 0x3a, 0xb9, 0xf8,
	0x0f, 0xc4, 0xc1, 0x20, 0x42, 0x88, 0xa3, 0x53, 0x5b, 0xcf, 0xb6, 0x58, 0x12, 0x69, 0xea, 0xd0,
	0x7f, 0x2f, 0x3d, 0x0a, 0x76, 0x7b, 0xdf, 0xe7, 0x9e, 0xe1, 0x3d, 0x00, 0xe7, 0x1f, 0xb8, 0x7f,
	0xf7, 0x7e, 0xf0, 0x82, 0x4f, 0x39, 0x73, 0xc0, 0xb5, 0x7b, 0x7a, 0xb1, 0x81, 0x48, 0x1b, 0xc9,
	0x14, 0xcb, 0xff, 0x6d, 0xa4, 0x8d, 0x10, 0xc0, 0x8d, 0xef, 0x07, 0x19, 0x11, 0xa1, 0x2c, 0x76,
	0x90, 0x98, 0x4f, 0x79, 0xc1, 0x51, 0xc6, 0x8a, 0xe5, 0xa9, 0x9d, 0xdb, 0xe4, 0x5a, 0xdf, 0xa1,
	0xe4, 0x8a, 0xe5, 0x6b, 0x4b, 0x99, 0x5c, 0xc4, 0x5e, 0x9f, 0xe4, 0xdf, 0xec, 0x52, 0xcb, 0xee,
	0xb0, 0x3d, 0x76, 0xbe, 0x7a, 0x55, 0x4d, 0xd1, 0xba, 0xdb, 0xe8, 0xaa, 0x2b, 0x86, 0x50, 0xd4,
	0x28, 0x14, 0xac, 0xe8, 0x70, 0xc6, 0xb6, 0x6e, 0x06, 0x5a, 0x12, 0xdb, 0x25, 0xfa, 0x19, 0x45,
	0x68, 0x30, 0xd0, 0xb2, 0xd4, 0x2e, 0x51, 0x99, 0xd0, 0x67, 0x87, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xaa, 0xc0, 0xff, 0x0d, 0xe7, 0x00, 0x00, 0x00,
}
