// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package node

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Info struct {
	IP                   string   `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=Port,proto3" json:"Port,omitempty"`
	PubKey               []byte   `protobuf:"bytes,3,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	Role                 uint32   `protobuf:"varint,4,opt,name=Role,proto3" json:"Role,omitempty"`
	PeerID               []byte   `protobuf:"bytes,5,opt,name=PeerID,proto3" json:"PeerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *Info) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Info) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Info) GetRole() uint32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *Info) GetPeerID() []byte {
	if m != nil {
		return m.PeerID
	}
	return nil
}

type BlockchainSyncMessage struct {
	BlockHeight          int64    `protobuf:"varint,1,opt,name=BlockHeight,proto3" json:"BlockHeight,omitempty"`
	BlockHashes          []byte   `protobuf:"bytes,2,opt,name=BlockHashes,proto3" json:"BlockHashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockchainSyncMessage) Reset()         { *m = BlockchainSyncMessage{} }
func (m *BlockchainSyncMessage) String() string { return proto.CompactTextString(m) }
func (*BlockchainSyncMessage) ProtoMessage()    {}
func (*BlockchainSyncMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

func (m *BlockchainSyncMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockchainSyncMessage.Unmarshal(m, b)
}
func (m *BlockchainSyncMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockchainSyncMessage.Marshal(b, m, deterministic)
}
func (m *BlockchainSyncMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockchainSyncMessage.Merge(m, src)
}
func (m *BlockchainSyncMessage) XXX_Size() int {
	return xxx_messageInfo_BlockchainSyncMessage.Size(m)
}
func (m *BlockchainSyncMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockchainSyncMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BlockchainSyncMessage proto.InternalMessageInfo

func (m *BlockchainSyncMessage) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *BlockchainSyncMessage) GetBlockHashes() []byte {
	if m != nil {
		return m.BlockHashes
	}
	return nil
}

type PingMessageType struct {
	Version              uint32   `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Node                 *Info    `protobuf:"bytes,2,opt,name=Node,proto3" json:"Node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMessageType) Reset()         { *m = PingMessageType{} }
func (m *PingMessageType) String() string { return proto.CompactTextString(m) }
func (*PingMessageType) ProtoMessage()    {}
func (*PingMessageType) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{2}
}

func (m *PingMessageType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessageType.Unmarshal(m, b)
}
func (m *PingMessageType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessageType.Marshal(b, m, deterministic)
}
func (m *PingMessageType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessageType.Merge(m, src)
}
func (m *PingMessageType) XXX_Size() int {
	return xxx_messageInfo_PingMessageType.Size(m)
}
func (m *PingMessageType) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessageType.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessageType proto.InternalMessageInfo

func (m *PingMessageType) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PingMessageType) GetNode() *Info {
	if m != nil {
		return m.Node
	}
	return nil
}

type PongMessageType struct {
	ShardID              uint32   `protobuf:"varint,1,opt,name=ShardID,proto3" json:"ShardID,omitempty"`
	Version              uint32   `protobuf:"varint,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Peers                []*Info  `protobuf:"bytes,3,rep,name=Peers,proto3" json:"Peers,omitempty"`
	PubKeys              [][]byte `protobuf:"bytes,4,rep,name=PubKeys,proto3" json:"PubKeys,omitempty"`
	LeaderPubKey         []byte   `protobuf:"bytes,5,opt,name=LeaderPubKey,proto3" json:"LeaderPubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongMessageType) Reset()         { *m = PongMessageType{} }
func (m *PongMessageType) String() string { return proto.CompactTextString(m) }
func (*PongMessageType) ProtoMessage()    {}
func (*PongMessageType) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{3}
}

func (m *PongMessageType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongMessageType.Unmarshal(m, b)
}
func (m *PongMessageType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongMessageType.Marshal(b, m, deterministic)
}
func (m *PongMessageType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongMessageType.Merge(m, src)
}
func (m *PongMessageType) XXX_Size() int {
	return xxx_messageInfo_PongMessageType.Size(m)
}
func (m *PongMessageType) XXX_DiscardUnknown() {
	xxx_messageInfo_PongMessageType.DiscardUnknown(m)
}

var xxx_messageInfo_PongMessageType proto.InternalMessageInfo

func (m *PongMessageType) GetShardID() uint32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *PongMessageType) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PongMessageType) GetPeers() []*Info {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *PongMessageType) GetPubKeys() [][]byte {
	if m != nil {
		return m.PubKeys
	}
	return nil
}

func (m *PongMessageType) GetLeaderPubKey() []byte {
	if m != nil {
		return m.LeaderPubKey
	}
	return nil
}

func init() {
	proto.RegisterType((*Info)(nil), "node.Info")
	proto.RegisterType((*BlockchainSyncMessage)(nil), "node.BlockchainSyncMessage")
	proto.RegisterType((*PingMessageType)(nil), "node.PingMessageType")
	proto.RegisterType((*PongMessageType)(nil), "node.PongMessageType")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x0d, 0xb0, 0xad, 0x71, 0x4a, 0x6d, 0xb2, 0x89, 0x66, 0x4f, 0x66, 0xc3, 0x89, 0x53, 0x0f,
	0xfa, 0x07, 0xa6, 0x07, 0x49, 0xd5, 0x6c, 0xb6, 0xc6, 0x8b, 0x27, 0x5a, 0x46, 0x20, 0x36, 0xbb,
	0xcd, 0x2e, 0x1e, 0xf8, 0x20, 0xff, 0xd3, 0x30, 0x40, 0xa4, 0x7a, 0x9b, 0xf7, 0xe6, 0xf1, 0xde,
	0xf0, 0x16, 0xc0, 0xd8, 0x02, 0xd7, 0x27, 0x67, 0x1b, 0xcb, 0x59, 0x37, 0x27, 0x06, 0x58, 0x66,
	0x3e, 0x2c, 0xbf, 0x82, 0x30, 0x53, 0x22, 0x90, 0x41, 0x7a, 0xa9, 0xc3, 0x4c, 0x71, 0x0e, 0x4c,
	0x59, 0xd7, 0x88, 0x90, 0x18, 0x9a, 0xf9, 0x0d, 0xcc, 0xd5, 0xd7, 0x7e, 0x8b, 0xad, 0x88, 0x64,
	0x90, 0xc6, 0x7a, 0x40, 0x9d, 0x56, 0xdb, 0x23, 0x0a, 0x26, 0x83, 0x74, 0xa9, 0x69, 0x26, 0x2d,
	0xa2, 0xcb, 0x36, 0x62, 0x36, 0x68, 0x09, 0x25, 0xef, 0x70, 0xfd, 0x70, 0xb4, 0x87, 0xcf, 0x43,
	0x95, 0xd7, 0x66, 0xd7, 0x9a, 0xc3, 0x33, 0x7a, 0x9f, 0x97, 0xc8, 0x25, 0x2c, 0x68, 0xf1, 0x88,
	0x75, 0x59, 0x35, 0x74, 0x49, 0xa4, 0xa7, 0xd4, 0xaf, 0x22, 0xf7, 0x15, 0x7a, 0xba, 0x2c, 0xd6,
	0x53, 0x2a, 0xd9, 0xc2, 0x4a, 0xd5, 0xa6, 0x1c, 0x2c, 0x5f, 0xdb, 0x13, 0x72, 0x01, 0x17, 0x6f,
	0xe8, 0x7c, 0x6d, 0x0d, 0x59, 0x2e, 0xf5, 0x08, 0xf9, 0x2d, 0xb0, 0x17, 0x5b, 0x20, 0xf9, 0x2c,
	0xee, 0x60, 0x4d, 0xd5, 0x74, 0x5d, 0x68, 0xe2, 0x93, 0xef, 0x00, 0x56, 0xca, 0xfe, 0x73, 0xdb,
	0x55, 0xb9, 0x2b, 0xb2, 0xcd, 0xe8, 0x36, 0xc0, 0x69, 0x4e, 0x78, 0x9e, 0x23, 0x61, 0xd6, 0xfd,
	0xbb, 0x17, 0x91, 0x8c, 0xfe, 0x04, 0xf5, 0x8b, 0xee, 0xdb, 0xbe, 0x49, 0x2f, 0x98, 0x8c, 0xd2,
	0x58, 0x8f, 0x90, 0x27, 0x10, 0x3f, 0x61, 0x5e, 0xa0, 0x1b, 0x7a, 0xef, 0xbb, 0x3c, 0xe3, 0xf6,
	0x73, 0x7a, 0xce, 0xfb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x9a, 0x14, 0x68, 0xdc, 0x01,
	0x00, 0x00,
}
